version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inboxcoin
      MYSQL_USER: inboxcoin
      MYSQL_PASSWORD: inboxcoin
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
